import {chromium} from 'playwright';
import fs from 'node:fs/promises';
await fs.mkdir('test-results/study-preview',{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
page.on('pageerror',e=>console.log('PAGE ERROR',e.message));
await page.goto('http://127.0.0.1:5173');
await page.waitForTimeout(1200);
await page.getByLabel('Как к тебе обращаться?').fill('Алекс');
await page.getByRole('button',{name:'Начнём знакомство'}).click();
await page.waitForTimeout(600);
console.log((await page.locator('body').innerText()).slice(0,9000));
await page.screenshot({path:'test-results/study-preview/home.png',fullPage:true});
await page.getByRole('button',{name:'Темы ЕГЭ',exact:true}).click();
await page.getByLabel('Поиск по всем темам ЕГЭ').fill('модуль');
await page.waitForTimeout(400);
await page.screenshot({path:'test-results/study-preview/catalog.png',fullPage:true});
await page.locator('.curriculum-node').first().click();
await page.screenshot({path:'test-results/study-preview/topic.png',fullPage:true});
await page.getByRole('button',{name:'Объяснение в сцене',exact:true}).click();
await page.waitForTimeout(1400);
await page.screenshot({path:'test-results/study-preview/scene.png',fullPage:true});
await browser.close();
